name: Deploy to Surge

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Install Surge
      run: npm install --global surge
      
    - name: Deploy to Surge
      run: surge /build squealing-cent.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}